# AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
# Generated by tools/generate_jax_variants.py
# Source module: operators/survival/rank_and_crowding/classes.py

try:
    import jax.numpy as np
    _HAS_JAX = True
except Exception:
    import numpy as np
    _HAS_JAX = False
from pymoo.core.population import Population
from pymoo.core.survival import Survival, split_by_feasibility
from pymoo.operators.survival.rank_and_crowding.metrics import get_crowding_function
from pymoo.util.nds.non_dominated_sorting import NonDominatedSorting
from pymoo.util.randomized_argsort import randomized_argsort

class RankAndCrowding(Survival):

    def __init__(self, nds=None, crowding_func='cd'):
        """
        A generalization of the NSGA-II survival operator that ranks individuals by dominance criteria
        and sorts the last front by some user-specified crowding metric. The default is NSGA-II's crowding distances
        although others might be more effective.

        For many-objective problems, try using 'mnn' or '2nn'.

        For Bi-objective problems, 'pcd' is very effective.

        Parameters
        ----------
        nds : str or None, optional
            Pymoo type of non-dominated sorting. Defaults to None.

        crowding_func : str or callable, optional
            Crowding metric. Options are:

                - 'cd': crowding distances
                - 'pcd' or 'pruning-cd': improved pruning based on crowding distances
                - 'ce': crowding entropy
                - 'mnn': M-Neaest Neighbors
                - '2nn': 2-Neaest Neighbors

            If callable, it has the form ``fun(F, filter_out_duplicates=None, n_remove=None, **kwargs)``
            in which F (n, m) and must return metrics in a (n,) array.

            The options 'pcd', 'cd', and 'ce' are recommended for two-objective problems, whereas 'mnn' and '2nn' for many objective.
            When using 'pcd', 'mnn', or '2nn', individuals are already eliminated in a 'single' manner. 
            Due to Cython implementation, they are as fast as the corresponding 'cd', 'mnn-fast', or '2nn-fast', 
            although they can singnificantly improve diversity of solutions.
            Defaults to 'cd'.
        """
        crowding_func_ = get_crowding_function(crowding_func)
        super().__init__(filter_infeasible=True)
        self.nds = nds if nds is not None else NonDominatedSorting()
        self.crowding_func = crowding_func_

    def _do(self, problem, pop, *args, random_state=None, n_survive=None, **kwargs):
        F = pop.get('F').astype(float, copy=False)
        survivors = []
        fronts = self.nds.do(F, n_stop_if_ranked=n_survive)
        for k, front in enumerate(fronts):
            I = np.arange(len(front))
            if len(survivors) + len(I) > n_survive:
                n_remove = len(survivors) + len(front) - n_survive
                crowding_of_front = self.crowding_func.do(F[front, :], n_remove=n_remove)
                I = randomized_argsort(crowding_of_front, order='descending', method='numpy', random_state=random_state)
                I = I[:-n_remove]
            else:
                crowding_of_front = self.crowding_func.do(F[front, :], n_remove=0)
            for j, i in enumerate(front):
                pop[i].set('rank', k)
                pop[i].set('crowding', crowding_of_front[j])
            survivors.extend(front[I])
        return pop[survivors]

class ConstrRankAndCrowding(Survival):

    def __init__(self, nds=None, crowding_func='cd'):
        """
        The Rank and Crowding survival approach for handling constraints proposed on
        GDE3 by Kukkonen, S. & Lampinen, J. (2005).

        Parameters
        ----------
        nds : str or None, optional
            Pymoo type of non-dominated sorting. Defaults to None.

        crowding_func : str or callable, optional
            Crowding metric. Options are:

                - 'cd': crowding distances
                - 'pcd' or 'pruning-cd': improved pruning based on crowding distances
                - 'ce': crowding entropy
                - 'mnn': M-Neaest Neighbors
                - '2nn': 2-Neaest Neighbors

            If callable, it has the form ``fun(F, filter_out_duplicates=None, n_remove=None, **kwargs)``
            in which F (n, m) and must return metrics in a (n,) array.

            The options 'pcd', 'cd', and 'ce' are recommended for two-objective problems, whereas 'mnn' and '2nn' for many objective.
            When using 'pcd', 'mnn', or '2nn', individuals are already eliminated in a 'single' manner. 
            Due to Cython implementation, they are as fast as the corresponding 'cd', 'mnn-fast', or '2nn-fast', 
            although they can singnificantly improve diversity of solutions.
            Defaults to 'cd'.
        """
        super().__init__(filter_infeasible=False)
        self.nds = nds if nds is not None else NonDominatedSorting()
        self.ranking = RankAndCrowding(nds=nds, crowding_func=crowding_func)

    def _do(self, problem, pop, *args, n_survive=None, **kwargs):
        if n_survive is None:
            n_survive = len(pop)
        n_survive = min(n_survive, len(pop))
        if problem.n_constr > 0:
            feas, infeas = split_by_feasibility(pop, sort_infeas_by_cv=True, sort_feas_by_obj=False, return_pop=False)
            n_feas = len(feas)
            if n_feas == 0:
                survivors = Population()
            else:
                survivors = self.ranking.do(problem, pop[feas], *args, n_survive=min(len(feas), n_survive), **kwargs)
            n_remaining = n_survive - len(survivors)
            if n_remaining > 0:
                G = pop[infeas].get('G')
                G = np.maximum(G, 0)
                H = pop[infeas].get('H')
                H = np.absolute(H)
                C = np.column_stack((G, H))
                infeas_fronts = self.nds.do(C, n_stop_if_ranked=n_remaining)
                for k, front in enumerate(infeas_fronts):
                    pop[infeas][front].set('cv_rank', k)
                    if len(survivors) + len(front) > n_survive:
                        CV = pop[infeas][front].get('CV').flatten()
                        I = randomized_argsort(CV, order='ascending', method='numpy')
                        I = I[:n_survive - len(survivors)]
                    else:
                        I = np.arange(len(front))
                    survivors = Population.merge(survivors, pop[infeas][front[I]])
        else:
            survivors = self.ranking.do(problem, pop, *args, n_survive=n_survive, **kwargs)
        return survivors
RankAndCrowding_JAX = RankAndCrowding
ConstrRankAndCrowding_JAX = ConstrRankAndCrowding
