# AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
# Generated by tools/generate_jax_variants.py
# Source module: operators/crossover/dex.py

try:
    import jax.numpy as np
    _HAS_JAX = True
except Exception:
    import numpy as np
    _HAS_JAX = False
from pymoo.core.crossover import Crossover
from pymoo.core.population import Population
from pymoo.operators.crossover.binx import mut_binomial
from pymoo.operators.crossover.expx import mut_exp
from pymoo.operators.repair.bounds_repair import is_out_of_bounds_by_problem, repair_random_init
from pymoo.util import default_random_state

@default_random_state
def de_differential(X, F, dither=None, jitter=True, gamma=0.0001, return_differentials=False, random_state=None):
    n_parents, n_matings, n_var = X.shape
    assert n_parents % 2 == 1, 'For the differential an odd number of values need to be provided'
    F = np.ones(n_matings) * F
    pairs = (np.arange(n_parents - 1) + 1).reshape(-1, 2)
    diffs = np.zeros((n_matings, n_var))
    for i, j in pairs:
        if dither == 'vector':
            F = F + random_state.random(n_matings) * (1 - F)
        elif dither == 'scalar':
            F = F + random_state.random() * (1 - F)
        if jitter:
            F = F * (1 + gamma * (random_state.random(n_matings) - 0.5))
        diffs += F[:, None] * (X[i] - X[j])
    Xp = X[0] + diffs
    if return_differentials:
        return (Xp, diffs)
    else:
        return Xp

class DEX(Crossover):

    def __init__(self, F=None, CR=0.7, variant='bin', dither=None, jitter=False, n_diffs=1, n_iter=1, at_least_once=True, **kwargs):
        super().__init__(1 + 2 * n_diffs, 1, **kwargs)
        self.n_diffs = n_diffs
        self.F = F
        self.CR = CR
        self.variant = variant
        self.at_least_once = at_least_once
        self.dither = dither
        self.jitter = jitter
        self.n_iter = n_iter

    def do(self, problem, pop, parents=None, *args, random_state, **kwargs):
        if parents is not None:
            pop = [pop[mating] for mating in parents]
        X = np.swapaxes(np.array([[parent.get('X') for parent in mating] for mating in pop]), 0, 1).copy()
        n_parents, n_matings, n_var = X.shape
        m = np.arange(n_matings)
        F = self.F if self.F is not None else rnd_F(m, random_state=random_state)
        Xp = de_differential(X[:, m], F, random_state=random_state)
        if problem.has_bounds():
            for k in range(self.n_iter):
                m = is_out_of_bounds_by_problem(problem, Xp)
                F = rnd_F(m, random_state=random_state)
                Xp[m] = de_differential(X[:, m], F, random_state=random_state)
            Xp = repair_random_init(Xp, X[0], *problem.bounds())
        if self.variant == 'bin':
            M = mut_binomial(n_matings, n_var, self.CR, at_least_once=self.at_least_once, random_state=random_state)
        elif self.variant == 'exp':
            M = mut_exp(n_matings, n_var, self.CR, at_least_once=self.at_least_once, random_state=random_state)
        else:
            raise Exception(f'Unknown variant: {self.variant}')
        X = X[0]
        X[M] = Xp[M]
        return Population.new('X', X)

@default_random_state
def rnd_F(m, random_state=None):
    return 0.5 * (1 + random_state.uniform(size=len(m)))
DEX_JAX = DEX
