# AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
# Generated by tools/generate_jax_variants.py
# Source module: operators/crossover/expx.py

try:
    import jax.numpy as np
    _HAS_JAX = True
except Exception:
    import numpy as np
    _HAS_JAX = False
from pymoo.core.crossover import Crossover
from pymoo.core.variable import get, Real
from pymoo.util import default_random_state
from pymoo.util.misc import crossover_mask, row_at_least_once_true

@default_random_state
def mut_exp(n_matings, n_var, prob, at_least_once=True, random_state=None):
    assert len(prob) == n_matings
    M = np.full((n_matings, n_var), False)
    s = random_state.integers(0, n_var, size=n_matings)
    for i in range(n_matings):
        start = s[i]
        for j in range(n_var):
            current = (start + j) % n_var
            if random_state.random() <= prob[i]:
                M[i, current] = True
            else:
                break
    if at_least_once:
        M = row_at_least_once_true(M, random_state=random_state)
    return M

class ExponentialCrossover(Crossover):

    def __init__(self, prob_exp=0.75, **kwargs):
        super().__init__(2, 2, **kwargs)
        self.prob_exp = Real(prob_exp, bounds=(0.5, 0.9), strict=(0.0, 1.0))

    def _do(self, _, X, random_state=None, **kwargs):
        _, n_matings, n_var = X.shape
        prob_exp = get(self.prob_exp, size=n_matings)
        M = mut_exp(n_matings, n_var, prob_exp, at_least_once=True, random_state=random_state)
        _X = crossover_mask(X, M)
        return _X
ExponentialCrossover_JAX = ExponentialCrossover
