# AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
# Generated by tools/generate_jax_variants.py
# Source module: operators/crossover/nox.py

try:
    import jax.numpy as np
    _HAS_JAX = True
except Exception:
    import numpy as np
    _HAS_JAX = False
from pymoo.core.crossover import Crossover
from pymoo.core.population import Population

class NoCrossover(Crossover):

    def __init__(self, *, n_parents=1, n_offsprings=None, prob=0.0, **kwargs):
        if n_offsprings is None:
            n_offsprings = n_parents
        super().__init__(n_parents, n_offsprings, prob, **kwargs)

    def do(self, problem, pop, *args, random_state, **kwargs):
        offsprings = []
        for parents in pop:
            if self.n_offsprings < self.n_parents:
                offsprings.extend(random_state.choice(parents, size=self.n_offsprings, replace=False))
            elif self.n_offsprings == self.n_parents:
                offsprings.extend(parents)
            else:
                offsprings.extend(parents)
                extra = self.n_offsprings - self.n_parents
                offsprings.extend(random_state.choice(parents, size=extra, replace=True))
        return Population.create(*offsprings)
NoCrossover_JAX = NoCrossover
