# AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
# Generated by tools/generate_jax_variants.py
# Source module: operators/crossover/sbx.py

try:
    import jax.numpy as np
    _HAS_JAX = True
except Exception:
    import numpy as np
    _HAS_JAX = False
from pymoo.core.crossover import Crossover
from pymoo.core.variable import Real, get
from pymoo.operators.repair.bounds_repair import repair_clamp
from pymoo.util import default_random_state

@default_random_state
def cross_sbx(X, xl, xu, eta, prob_var, prob_bin, eps=1e-14, random_state=None):
    n_parents, n_matings, n_var = X.shape
    cross = random_state.random((n_matings, n_var)) < prob_var
    too_close = np.abs(X[0] - X[1]) <= eps
    cross[too_close] = False
    cross[:, xl == xu] = False
    p1 = X[0][cross]
    p2 = X[1][cross]
    sm = p1 < p2
    y1 = np.where(sm, p1, p2)
    y2 = np.where(sm, p2, p1)
    _xl = np.repeat(xl[None, :], n_matings, axis=0)[cross]
    _xu = np.repeat(xu[None, :], n_matings, axis=0)[cross]
    eta = eta.repeat(n_var, axis=1)[cross]
    prob_bin = prob_bin.repeat(n_var, axis=1)[cross]
    rand = random_state.random(len(eta))

    def calc_betaq(beta):
        alpha = 2.0 - np.power(beta, -(eta + 1.0))
        mask, mask_not = (rand <= 1.0 / alpha, rand > 1.0 / alpha)
        betaq = np.zeros(mask.shape)
        betaq[mask] = np.power(rand * alpha, 1.0 / (eta + 1.0))[mask]
        betaq[mask_not] = np.power(1.0 / (2.0 - rand * alpha), 1.0 / (eta + 1.0))[mask_not]
        return betaq
    delta = y2 - y1
    beta = 1.0 + 2.0 * (y1 - _xl) / delta
    betaq = calc_betaq(beta)
    c1 = 0.5 * (y1 + y2 - betaq * delta)
    beta = 1.0 + 2.0 * (_xu - y2) / delta
    betaq = calc_betaq(beta)
    c2 = 0.5 * (y1 + y2 + betaq * delta)
    child1 = np.where(sm, c1, c2)
    child2 = np.where(sm, c2, c1)
    b = np.bitwise_xor(random_state.random(len(prob_bin)) < prob_bin, X[0, cross] > X[1, cross])
    child1, child2 = np.where(b, (child2, child1), (child1, child2))
    Q = np.copy(X)
    Q[0, cross] = child1
    Q[1, cross] = child2
    Q[0] = repair_clamp(Q[0], xl, xu)
    Q[1] = repair_clamp(Q[1], xl, xu)
    return Q

class SimulatedBinaryCrossover(Crossover):

    def __init__(self, prob_var=0.5, eta=15, prob_exch=1.0, prob_bin=0.5, n_offsprings=2, **kwargs):
        super().__init__(2, n_offsprings, **kwargs)
        self.prob_var = Real(prob_var, bounds=(0.1, 0.9))
        self.eta = Real(eta, bounds=(3.0, 30.0), strict=(1.0, None))
        self.prob_exch = Real(prob_exch, bounds=(0.0, 1.0), strict=(0.0, 1.0))
        self.prob_bin = Real(prob_bin, bounds=(0.0, 1.0), strict=(0.0, 1.0))

    def _do(self, problem, X, *args, random_state=None, **kwargs):
        _, n_matings, _ = X.shape
        eta, prob_var, prob_exch, prob_bin = get(self.eta, self.prob_var, self.prob_exch, self.prob_bin, size=(n_matings, 1))
        rand = random_state.random((len(prob_bin), 1))
        prob_bin[rand > prob_exch] = 0.0
        Q = cross_sbx(X.astype(float), problem.xl, problem.xu, eta, prob_var, prob_bin, random_state=random_state)
        if self.n_offsprings == 1:
            rand = random_state.random(size=n_matings) < 0.5
            Q[0, rand] = Q[1, rand]
            Q = Q[[0]]
        return Q

class SBX(SimulatedBinaryCrossover):
    pass
SimulatedBinaryCrossover_JAX = SimulatedBinaryCrossover
SBX_JAX = SBX
