# AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
# Generated by tools/generate_jax_variants.py
# Source module: operators/crossover/spx.py

try:
    import jax.numpy as np
    _HAS_JAX = True
except Exception:
    import numpy as np
    _HAS_JAX = False
from pymoo.operators.crossover.pntx import SinglePointCrossover

class SPX(SinglePointCrossover):
    pass
SPX_JAX = SPX
