# AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
# Generated by tools/generate_jax_variants.py
# Source module: operators/crossover/ux.py

try:
    import jax.numpy as np
    _HAS_JAX = True
except Exception:
    import numpy as np
    _HAS_JAX = False
from pymoo.core.crossover import Crossover
from pymoo.util.misc import crossover_mask

class UniformCrossover(Crossover):

    def __init__(self, **kwargs):
        super().__init__(2, 2, **kwargs)

    def _do(self, _, X, random_state=None, **kwargs):
        _, n_matings, n_var = X.shape
        M = random_state.random((n_matings, n_var)) < 0.5
        _X = crossover_mask(X, M)
        return _X

class UX(UniformCrossover):
    pass
UniformCrossover_JAX = UniformCrossover
UX_JAX = UX
